// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: short_url.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type URL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *URL) Reset() {
	*x = URL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_short_url_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *URL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URL) ProtoMessage() {}

func (x *URL) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URL.ProtoReflect.Descriptor instead.
func (*URL) Descriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{0}
}

func (x *URL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AddURLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Url  *URL   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *AddURLRequest) Reset() {
	*x = AddURLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_short_url_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddURLRequest) ProtoMessage() {}

func (x *AddURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddURLRequest.ProtoReflect.Descriptor instead.
func (*AddURLRequest) Descriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{1}
}

func (x *AddURLRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AddURLRequest) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

type AddURLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url   *URL   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // ошибка
}

func (x *AddURLResponse) Reset() {
	*x = AddURLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_short_url_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddURLResponse) ProtoMessage() {}

func (x *AddURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_short_url_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddURLResponse.ProtoReflect.Descriptor instead.
func (*AddURLResponse) Descriptor() ([]byte, []int) {
	return file_short_url_proto_rawDescGZIP(), []int{2}
}

func (x *AddURLResponse) GetUrl() *URL {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *AddURLResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_short_url_proto protoreflect.FileDescriptor

var file_short_url_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a, 0x03, 0x55, 0x52, 0x4c, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x41, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x22, 0x44, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x52, 0x4c, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0x3d, 0x0a, 0x04, 0x55, 0x52,
	0x4c, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x52,
	0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x68, 0x61, 0x57, 0x50, 0x2f,
	0x59, 0x61, 0x50, 0x72, 0x61, 0x63, 0x74, 0x69, 0x63, 0x75, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x2f,
	0x63, 0x6d, 0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_short_url_proto_rawDescOnce sync.Once
	file_short_url_proto_rawDescData = file_short_url_proto_rawDesc
)

func file_short_url_proto_rawDescGZIP() []byte {
	file_short_url_proto_rawDescOnce.Do(func() {
		file_short_url_proto_rawDescData = protoimpl.X.CompressGZIP(file_short_url_proto_rawDescData)
	})
	return file_short_url_proto_rawDescData
}

var file_short_url_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_short_url_proto_goTypes = []interface{}{
	(*URL)(nil),            // 0: proto.URL
	(*AddURLRequest)(nil),  // 1: proto.AddURLRequest
	(*AddURLResponse)(nil), // 2: proto.AddURLResponse
}
var file_short_url_proto_depIdxs = []int32{
	0, // 0: proto.AddURLRequest.url:type_name -> proto.URL
	0, // 1: proto.AddURLResponse.url:type_name -> proto.URL
	1, // 2: proto.URLs.AddURL:input_type -> proto.AddURLRequest
	2, // 3: proto.URLs.AddURL:output_type -> proto.AddURLResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_short_url_proto_init() }
func file_short_url_proto_init() {
	if File_short_url_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_short_url_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*URL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_short_url_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddURLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_short_url_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddURLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_short_url_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_short_url_proto_goTypes,
		DependencyIndexes: file_short_url_proto_depIdxs,
		MessageInfos:      file_short_url_proto_msgTypes,
	}.Build()
	File_short_url_proto = out.File
	file_short_url_proto_rawDesc = nil
	file_short_url_proto_goTypes = nil
	file_short_url_proto_depIdxs = nil
}
